-- ************************************ SqlDBM: Azure Synapse Analytics ***********************************
-- * Generated by SqlDBM: Azure Synapse analytics sample-20250204, v2 vs v1 by kushal.mangtani@sqldbm.com *

